package models

import "time"

// Client represents a device that connects to mediastorm
type Client struct {
	ID            string    `json:"id"`            // UUID generated by frontend
	UserID        string    `json:"userId"`        // Profile this client is associated with
	Name          string    `json:"name"`          // Admin-editable display name
	DeviceType    string    `json:"deviceType"`    // "iPhone", "iPad", "Apple TV", "Android Phone", "Android TV", etc.
	OS            string    `json:"os"`            // "iOS", "iPadOS", "tvOS", "Android"
	AppVersion    string    `json:"appVersion"`    // e.g., "1.2.1"
	LastSeenAt    time.Time `json:"lastSeenAt"`    // Last time client made a request
	FirstSeenAt   time.Time `json:"firstSeenAt"`   // When client first registered
	FilterEnabled bool      `json:"filterEnabled"` // Whether custom filtering is enabled for this client
}
